language: java

sudo: false

jdk:
  - oraclejdk8

node_js:
  - "4.2"

script:
  - mvn clean verify

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - renaud.pawlak@gmail.com
      - louis.grignon@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
