name: PR Checks
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: runs exhaustive tests
      run: |
        cd transpiler
        mvn install
        cd ..
        echo 'clone test repositories'
        git clone https://github.com/lgrignon/jsweet-java-runtime-transpilation-tests.git
        git clone https://github.com/lgrignon/j4ts-example.git
        echo 'transpile legacy j4ts sources'
        cd jsweet-java-runtime-transpilation-tests
        mvn clean generate-sources
        cd ..
        echo 'run j4ts tests'
        cd j4ts-example
        mvn clean compile && node target/j4ts-example-bundle.js


